### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: subtitles is not defined

### ISSUE THREAD

**Issue by WindedHero** [DEFENDORe/pseudotv#118]
I've set up a channel but I am unable to get anything to play, keeps stumbling across this error:

(node:19) UnhandledPromiseRejectionWarning: ReferenceError: subtitles is not defined
at FFMPEG.spawnError (/home/node/app/src/ffmpeg.js:45:84)
at FFMPEG.<anonymous> (/home/node/app/src/video.js:156:25)
at FFMPEG.emit (events.js:315:20)
at ChildProcess.<anonymous> (/home/node/app/src/ffmpeg.js:326:22)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 127)

(node:19) UnhandledPromiseRejectionWarning: ReferenceError: subtitles is not defined
at FFMPEG.spawnError (/home/node/app/src/ffmpeg.js:45:84)
at FFMPEG.<anonymous> (/home/node/app/src/video.js:156:25)
at FFMPEG.emit (events.js:315:20)
at ChildProcess.<anonymous> (/home/node/app/src/ffmpeg.js:326:22)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 127)

I am on `:dev` branch to enable forced direct play.

**Comment by WindedHero** [comment]
Changing path from `Direct` to `Plex`, setting the subtitle size to blank seems to have corrected the issue.

**Comment by ROODAY** [comment]
Do you have any more info? I tried doing the same thing (set subtitle to blank) and I'm on the dev branch, but the issue still persists. When I click a stream I see this a the top of the logs:
```
Stream starting. Channel: 3 (Easy Watching)
Plex transcoder initiated
Debug logging enabled
Getting stream
  deinterlace:     false
  streamPath:      plex
  forceDirectPlay: true
Direct play forced or native paths enabled
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80
```
Not sure what address this is referring to, I'm guessing this is part of the problem?
