### ISSUE TITLE
Docker image error with "opts being undefined"

### ISSUE THREAD

**Issue by vexorian** [DEFENDORe/pseudotv#42]
This error is specific to the docker image. When I installed the binary it worked perfectly.

- Installed and configured the channel and plex to use the DVR. Everything seemed to be going smoothly.
- Pressing the play button doens't work.
- docker-compose logs show this error:

pseudotv           | ReferenceError: opts is not defined
pseudotv           |     at ChildProcess.<anonymous> (/home/node/app/src/ffmpeg.js:168:58)
pseudotv           |     at ChildProcess.emit (events.js:310:20)
pseudotv           |     at maybeClose (internal/child_process.js:1021:16)
pseudotv           |     at Socket.<anonymous> (internal/child_process.js:443:11)
pseudotv           |     at Socket.emit (events.js:310:20)
pseudotv           |     at Pipe.<anonymous> (net.js:672:12)
pseudotv           | npm ERR! code ELIFECYCLE
pseudotv           | npm ERR! errno 1
pseudotv           | npm ERR! pseudotv@1.0.0 start: `node index.js`
pseudotv           | npm ERR! Exit status 1
pseudotv           | npm ERR! 
pseudotv           | npm ERR! Failed at the pseudotv@1.0.0 start script.

I am guessing this is a problem with the node version used by the Dockerfile.

**Comment by jonfairbanks** [comment]
Can we get this merged into master?

**Comment by vexorian** [comment]
Wouldn't it be nice?

I am basically in the process of forking the project cause the current official repo doesn't have active people with access to merge commits into it. We are releasing new test versions frequently and a stable version is coming soon to my repo at  https://github.com/vexorian/pseudotv

**Comment by jonfairbanks** [comment]
Nice, thanks for the info. I'll follow along over there.

**Comment by jonfairbanks** [comment]
@vexorian I checked over your repo and I see you do not currently have a docker image. Need any assistance with this? Docker is my primary use-case. 😅 

(Sorry for discussing here, I did not see the ability to open an issue/discussion on your repo)

**Comment by vexorian** [comment]
I use docker when developing it, I've just been hoping I didn't need to create my own docker hub registry and all that stuff.

**Comment by vexorian** [comment]
@jonfairbanks thanks for making me notice I don't have issues enabled. Also the fork is official now and we finallly have docker images in docker hub at https://github.com/vexorian/dizquetv

**Comment by jonfairbanks** [comment]
Heck yea, thank you!
