### ISSUE TITLE
Unraid with nVida P400

### ISSUE THREAD

**Issue by PaiSolutions** [DEFENDORe/pseudotv#51]
Docker crashing with nVidia unraid docker

`[h264_nvenc @ 0x560cd67281a0] Cannot load libcuda.so.1
Stream mapping:
Stream #0:0 (h264) -> null (graph 0)
null (graph 0) -> Stream #0:0 (h264_nvenc)
Stream #0:1 -> #0:1 (dts (dca) -> ac3 (native))
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
/home/node/app/src/ffmpeg.js:168
this.emit('error', { code: code, cmd: `${opts.ffmpegPath} ${tmpargs.join(' ')}` })
^

ReferenceError: opts is not defined
at ChildProcess.<anonymous> (/home/node/app/src/ffmpeg.js:168:58)
at ChildProcess.emit (events.js:310:20)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pseudotv@1.0.0 start: `node index.js`
npm ERR! Exit status 1

npm ERR! Failed at the pseudotv@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2020-06-06T08_49_20_078Z-debug.log`

Have plex linked to nVidia card.

**Comment by jonfairbanks** [comment]
Switch to `:dev` branch.
